services:
  spybot:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - static_files:/spybot_static
      - $PWD/.env:/.env
    expose:
      - 8000
  caddy:
    image: 'caddy:2.8-alpine'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
#      - "443:443"
#      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_files:/spybot_static
volumes:
  caddy_data:
  caddy_config:
  static_files:


