[tool.poetry]
name = "spybot2"
version = "0.1.0"
description = ""
authors = ["Benno <bensge@me.com>", "Justus <justus.fab@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2.3"
ts3 = "2.0.0b3"
django-environ = "^0.10.0"
mysqlclient = "^2.2.0"
django-crontab = "^0.7.1"
num2words = "^0.5.12"
requests = "^2.31.0"


[tool.poetry.group.test.dependencies]
unittest-xml-reporting = "^3.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
