services:
  spybot:
    image: 'ghcr.io/smofladru/spybot2:sha-${COMMIT_SHA}'
    restart: unless-stopped
    volumes:
      - static_files:/home/spybot/spybot_static
      - $PWD/.env:/app/.env
    expose:
      - 8000
  caddy:
    image: 'caddy:2.8-alpine'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "20001:20001"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_files:/spybot_static
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - spybot_pg_data:/var/lib/postgresql/data
    secrets:
      - db_password
  redis:
    image: redis:7.4.2-bookworm
volumes:
  caddy_data:
  caddy_config:
  static_files:
  spybot_pg_data:
secrets:
  db_password:
    file: secrets/db_password.txt


