name: Deploy to server via docker image

on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to Server manually
    needs: build-push-deploy-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: upload infrastructure files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SECONDARY_HOST }}
          username: ${{ secrets.SSH_SECONDARY_USERNAME }}
          password: ${{ secrets.SSH_SECONDARY_PASSWORD }}
          port: ${{ secrets.SSH_SECONDARY_PORT }}
          source: infrastructure/*
          target: .
      - name: execute remote ssh commands
        uses: appleboy/ssh-action@master
        env:
          SECRET: ${{ secrets.ENV_FILE }}
          COMMIT_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_SECONDARY_HOST }}
          username: ${{ secrets.SSH_SECONDARY_USERNAME }}
          password: ${{ secrets.SSH_SECONDARY_PASSWORD }}
          port: ${{ secrets.SSH_SECONDARY_PORT }}
          envs: SECRET,COMMIT_SHA
          script: |
            cd Spybot2
            echo "$SECRET" > .env
            docker-compose -f docker-compose-deploy.yml up
